# Generated by Django 5.2 on 2025-05-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="taken_over_by_staff",
            field=models.BooleanField(default=False),
        ),
    ]
